name: flutter_advanced_networkimage
description: An advanced image provider provides caching and retrying for flutter app. Now with zoomable widget and transition to image widget.
version: 0.5.0
author: "fuyumi <fnatic.roach@gmail.com>"
homepage: https://github.com/mchome/flutter_advanced_networkimage

dependencies:
  flutter:
    sdk: flutter
  http: "^0.13.1"
  path_provider: "^2.0.0"
  path: "^1.6.0"
  flutter_svg: "^0.21.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: "^1.6.0"

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.6.0 <2.0.0"
